### PR TITLE
Don't encode dates as datetimes by default

### LINKED ISSUE #37: dates are encoded as datetimes
https://github.com/agronholm/cbor2/blob/bf4acfd4ba08959a8b18f6c97981bae6d9bd22ca/cbor2/encoder.py#L156-L158

In my opinion the default behavior of the encoder should be to refuse to serialize an object if the decoder isn't capable of recreating it exactly. Converting to and from CBOR shouldn't be a lossy operation.

### PR DESCRIPTION
**Pull request by Changaco**
This branch fixes #37 but adds a flag to restore the old behavior. It may not be the most elegant solution, but it's the simplest one (that I know of).

### CODE REVIEW

**Comment by Changaco** [comment]
(CI isn't triggered for draft PRs?)

**Comment by Sekenre** [comment]
I'm happy with this

**Comment by agronholm** [comment]
So long as you remember that this constitutes a breaking API change.

**Comment by Changaco** [comment]
It's my first time writing CPython code, so someone more familiar with CPython should review it thoroughly.

**Comment by Sekenre** [comment]
Thanks for this, I found a difference in behaviour between the C version and Pure python,

If you change your test code as follows you'll see the difference:

```diff
diff --git a/tests/test_encoder.py b/tests/test_encoder.py
index 0eb29d6..db298ec 100644
--- a/tests/test_encoder.py
+++ b/tests/test_encoder.py
@@ -237,7 +237,7 @@ def test_datetime(impl, value, as_timestamp, expected):
 
 def test_date(impl):
     with pytest.raises(impl.CBOREncodeError):
-        impl.dumps(date(2013, 3, 21))
+        impl.dumps(date(2013, 3, 21), timezone=timezone.utc)
 
 
 def test_date_as_datetime(impl):
```

**Pull request merged**
