### PR TITLE
Added pre-commit configuration and fixed reported errors

### PR DESCRIPTION
**Pull request by agronholm**
This delegates linting checks to pre-commit.ci which has the ability to automatically fix some reported linting errors in PRs.

This also moves tool configuration to pyproject.toml.

### CODE REVIEW

**Comment by Sekenre** [comment]
Looks great! I've started using pre-commit at work.

**Comment by agronholm** [comment]
I think I have all the changes in that I wanted. Given the nature of the PR, it touches quite a lot of files. If you would like to switch to Black or something else while at it, now would be a good time.

**Comment by agronholm** [comment]
@Sekenre so do you want me to add Black too? I've adopted that in a lot of my projects lately, and never looked back.

**Comment by Sekenre** [comment]
@agronholm  Hi sorry I've been quiet, off on vacation. Absolutely happy with Black. Recently adopted it at work, it's nice to have things consistent across projects.

**Comment by agronholm** [comment]
@Sekenre Ok, Black is now part of the PR.

**Review by Sekenre — APPROVED** [review]
Looks great. Took me a while to get testing working because my old version of tox didn't understand pyproject.toml

**Comment by agronholm** [comment]
Thanks for reviewing.

**Pull request merged**
