### PR TITLE
String references

### PR DESCRIPTION
**Pull request by xurtis**
This adds the ability to decode [string references](http://cbor.schmorp.de/stringref) to both the C and Python decoders.

I've not worked on Python & C interop before, so I may have missed some things.

### CODE REVIEW

**Comment by Sekenre** [comment]
Thanks @xurtis This looks useful, do you plan to write an encoder? Without round-trip encode/decode I can't actually make use of this feature.

**Comment by xurtis** [comment]
Should be able to add an encoder without too much trouble.

**Comment by xurtis** [comment]
@sekenre I've updated the PR to include an encoder.

**Comment by agronholm** [comment]
This looks clean – do you have any remaining doubts about this PR @Sekenre ?

**Comment by Sekenre** [comment]
This is great thanks @xurtis, sorry about the wait.

**Pull request merged**
