### PR TITLE
Fix README & add a text link to the docs

### PR DESCRIPTION
**Pull request by Changaco**
Before:

screenshot_20190220_132652

After:

screenshot_20190220_132724

### CODE REVIEW

**Comment by agronholm** [comment]
LGTM

**Comment by agronholm** [comment]
How is the docs badge missing from your "before" screenshot?

**Comment by Changaco** [comment]
It's not just the badge that's missing, it's most of the first paragraph too. The two spaces at the beginning of that paragraph are the cause.

The "before" image is a screenshot of <https://github.com/agronholm/cbor2>, it's easy to see for yourself.

**Comment by agronholm** [comment]
Alright, thanks!

**Pull request merged**
