### PR TITLE
Make CBORTag hashable

### PR DESCRIPTION
**Pull request by nielstron**
This is a trivial solution to #147 by making the CBORTag hashable.

### CODE REVIEW

**Comment by nielstron** [comment]
There appears to be a test case that specifically checks that CBOR tags are not hashable - why is that the case? Because the class is not immutable? Why does this error have to be thrown when trying to *load* an object? The fact that it is not hashable should IMO not completely forbid it to be created at all or am I missing something?

The testcase: https://github.com/agronholm/cbor2/blob/aef7e88d3ef2bb6985ce4d8854f4a5ad5e860c04/tests/test_decoder.py#L701

**Comment by agronholm** [comment]
Did the test suite pass for you locally?

**Comment by agronholm** [comment]
@waveform80 could you comment? Why does `CBORTag` have to be unhashable?

**Comment by Sekenre** [comment]
That's brilliant! Thank you

**Comment by nielstron** [comment]
Follow up: Will there be a new minor version of the package with this fix included?

**Comment by agronholm** [comment]
Given that there are other changes (the no-arch wheel) that went into `master` recently, that would be nice. @Sekenre ?

**Comment by Sekenre** [comment]
Yup, coming out later today.

**Pull request merged**
