### PR TITLE
Build arm64 wheels for Linux, macOS

### PR DESCRIPTION
**Pull request by agronholm**
This also drops the building of musllinux wheels as they add a lot to the total build time. Your call though.

### CODE REVIEW

**Comment by agronholm** [comment]
Do we want to build 32-bit Windows wheels too?

**Comment by Sekenre** [comment]
We seem to have a lot of users that want to build Alpine Linux based Docker images, the musl wheel build is for their benefit. How much time would it add?

I'm ok with removing it as long as we include instructions for those users.

**Comment by agronholm** [comment]
If that is the case then the extra time building musl wheels would be justified. I'll add it back.

**Comment by agronholm** [comment]
All good now?

**Pull request merged**
