### PR TITLE
add option to not build c-extension

### PR DESCRIPTION
**Pull request by jschlyter**
updates #86

### CODE REVIEW

**Comment by agronholm** [comment]
There has to be a better way to make this optional.

**Comment by agronholm** [comment]
Curious that it's already set as optional (see [here](https://github.com/agronholm/cbor2/blob/master/setup.py#L37)). So which tool is failing to respect that?

**Comment by jschlyter** [comment]
> Curious that it's already set as optional (see [here](https://github.com/agronholm/cbor2/blob/master/setup.py#L37)). So which tool is failing to respect that?

Python 3.7 and 3.8 (from python.org and from homebrew) on MacOS builds extensions by default. I've found no other other way to disable building the extension.

**Comment by Sekenre** [comment]
There is a way to do this with pip or setuptools:

```
CC="/bin/true" pip install cbor2
```

This will skip building the c extension even if you have a compiler and compatible libc.

**Comment by Sekenre** [comment]
A cross-platform way to do this is to create a file called `pydistutils.cfg` in `$HOME` on unix or `%USERPROFILE%` on windows with this content:

```
[build_ext]
dry_run = 1
```

**Comment by jameshilliard** [comment]
I have an improved version of this in #92 which allows for fully overriding the auto-detection behavior.

**Comment by jschlyter** [comment]
Replaced by #92

**Pull request closed without merging**
