### PR TITLE
Added version to setup.cfg

### PR DESCRIPTION
**Pull request by SmithSamuelM**
pip complains when doing dependency checks because no version

### CODE REVIEW

**Comment by agronholm** [comment]
There would have to be a release process that keeps git tags in sync with the release versions.

**Comment by SmithSamuelM** [comment]
pip is not happy with a version that does not follow the 5.4.2 syntax  M.m.b   Your build is producting a version that is
5.4.2.post1
This is causing pip install  to fail

**Comment by agronholm** [comment]
> pip is not happy with a version that does not follow the 5.4.2 syntax M.m.b Your build is producting a version that is 5.4.2.post1 This is causing pip install to fail

What evidence do you have of this? And how do you explain the failure to install other versions?

**Comment by SmithSamuelM** [comment]
> What evidence do you have of this? And how do you explain the failure to install other versions?

See the errors above where pip is complaining about missing metadata for version. So maybe its supposed to support it but apparently doesnt.

See below.  

https://github.com/agronholm/cbor2/issues/130

```
Discarding https://files.pythonhosted.org/packages/36/0f/6c64c4b45bbe0249e65e61691615ef3fa9e89f0b31d69b04cd5e4078d293/cbor2-5.3.0.tar.gz#sha256=462b3604d9579458a79e6ca350943c49aabbc98c794c111a79b98720b9164336 (from https://pypi.org/simple/cbor2/) (requires-python:>=3.6): Requested cbor2 from https://files.pythonhosted.org/packages/36/0f/6c64c4b45bbe0249e65e61691615ef3fa9e89f0b31d69b04cd5e4078d293/cbor2-5.3.0.tar.gz#sha256=462b3604d9579458a79e6ca350943c49aabbc98c794c111a79b98720b9164336 has inconsistent version: filename has '5.3.0', but metadata has '0.0.0'
```

Also see further below.  that its creating `Finished processing dependencies for cbor2===5.4.2.post1.post3`

My fixes work. Your config doesn't.

```bash
cbor2 % python3 setup.py install
/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 5.4.2.post1.post2-dirty is an invalid version and will not be supported in a future release
  warnings.warn(
/opt/homebrew/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py:530: UserWarning: The version specified ('5.4.2.post1.post3') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
/opt/homebrew/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/homebrew/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 5.4.2.post1.post2-dirty is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 5.4.2.post1.post3 is an invalid version and will not be supported in a future release
  warnings.warn(
running egg_info
writing cbor2.egg-info/PKG-INFO
writing dependency_links to cbor2.egg-info/dependency_links.txt
writing requirements to cbor2.egg-info/requires.txt
writing top-level names to cbor2.egg-info/top_level.txt
adding license file 'LICENSE.txt'
writing manifest file 'cbor2.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-12-arm64/egg
running install_lib
running build_py
creating build/lib.macosx-12-arm64-cpython-310/cbor2
copying cbor2/decoder.py -> build/lib.macosx-12-arm64-cpython-310/cbor2
copying cbor2/__init__.py -> build/lib.macosx-12-arm64-cpython-310/cbor2
copying cbor2/types.py -> build/lib.macosx-12-arm64-cpython-310/cbor2
copying cbor2/encoder.py -> build/lib.macosx-12-arm64-cpython-310/cbor2
copying cbor2/tool.py -> build/lib.macosx-12-arm64-cpython-310/cbor2
running build_ext
creating build/bdist.macosx-12-arm64
creating build/bdist.macosx-12-arm64/egg
copying build/lib.macosx-12-arm64-cpython-310/_cbor2.cpython-310-darwin.so -> build/bdist.macosx-12-arm64/egg
creating build/bdist.macosx-12-arm64/egg/cbor2
copying build/lib.macosx-12-arm64-cpython-310/cbor2/decoder.py -> build/bdist.macosx-12-arm64/egg/cbor2
copying build/lib.macosx-12-arm64-cpython-310/cbor2/__init__.py -> build/bdist.macosx-12-arm64/egg/cbor2
copying build/lib.macosx-12-arm64-cpython-310/cbor2/types.py -> build/bdist.macosx-12-arm64/egg/cbor2
copying build/lib.macosx-12-arm64-cpython-310/cbor2/encoder.py -> build/bdist.macosx-12-arm64/egg/cbor2
copying build/lib.macosx-12-arm64-cpython-310/cbor2/tool.py -> build/bdist.macosx-12-arm64/egg/cbor2
byte-compiling build/bdist.macosx-12-arm64/egg/cbor2/decoder.py to decoder.cpython-310.pyc
byte-compiling build/bdist.macosx-12-arm64/egg/cbor2/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-12-arm64/egg/cbor2/types.py to types.cpython-310.pyc
byte-compiling build/bdist.macosx-12-arm64/egg/cbor2/encoder.py to encoder.cpython-310.pyc
byte-compiling build/bdist.macosx-12-arm64/egg/cbor2/tool.py to tool.cpython-310.pyc
creating stub loader for _cbor2.cpython-310-darwin.so
byte-compiling build/bdist.macosx-12-arm64/egg/_cbor2.py to _cbor2.cpython-310.pyc
creating build/bdist.macosx-12-arm64/egg/EGG-INFO
copying cbor2.egg-info/PKG-INFO -> build/bdist.macosx-12-arm64/egg/EGG-INFO
copying cbor2.egg-info/SOURCES.txt -> build/bdist.macosx-12-arm64/egg/EGG-INFO
copying cbor2.egg-info/dependency_links.txt -> build/bdist.macosx-12-arm64/egg/EGG-INFO
copying cbor2.egg-info/requires.txt -> build/bdist.macosx-12-arm64/egg/EGG-INFO
copying cbor2.egg-info/top_level.txt -> build/bdist.macosx-12-arm64/egg/EGG-INFO
writing build/bdist.macosx-12-arm64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__._cbor2.cpython-310: module references __file__
creating dist
creating 'dist/cbor2-5.4.2.post1.post3-py3.10-macosx-12-arm64.egg' and adding 'build/bdist.macosx-12-arm64/egg' to it
removing 'build/bdist.macosx-12-arm64/egg' (and everything under it)
Processing cbor2-5.4.2.post1.post3-py3.10-macosx-12-arm64.egg
creating /opt/homebrew/lib/python3.10/site-packages/cbor2-5.4.2.post1.post3-py3.10-macosx-12-arm64.egg
Extracting cbor2-5.4.2.post1.post3-py3.10-macosx-12-arm64.egg to /opt/homebrew/lib/python3.10/site-packages
Adding cbor2 5.4.2.post1.post3 to easy-install.pth file
/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 5.4.2.post1.post3 is an invalid version and will not be supported in a future release
  warnings.warn(

Installed /opt/homebrew/lib/python3.10/site-packages/cbor2-5.4.2.post1.post3-py3.10-macosx-12-arm64.egg
Processing dependencies for cbor2===5.4.2.post1.post3
Finished processing dependencies for cbor2===5.4.2.post1.post3
```

**Comment by agronholm** [comment]
Yes, entering a hard coded version directly in the packaging configuration surely works. But it doesn't solve the problem that this project uses setuptools_scm for: keeping git tags and releases in sync. There are other solutions to this and I'm sure the maintainer (@Sekenre) would be willing to consider those.

For the record, I was able to install from source just fine:
```
$ pip install --no-binary=cbor2 cbor2
Collecting cbor2
  Using cached cbor2-5.4.2.post1.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: cbor2
  Building wheel for cbor2 (PEP 517) ... done
  Created wheel for cbor2: filename=cbor2-5.4.2.post1-cp310-cp310-linux_x86_64.whl size=163340 sha256=94a567bbb62e062880bfef30b692e76bc4a35b94bdfd62f1d2bd748485db0590
  Stored in directory: /home/alex/.cache/pip/wheels/57/04/a7/8d10935f802003103d9a8e6e50d1e6383bcaf82e5b464412c1
Successfully built cbor2
Installing collected packages: cbor2
Successfully installed cbor2-5.4.2.post1
```

Are you in a position to use the [workaround](https://github.com/agronholm/cbor2/issues/130#issuecomment-1106898506) I offered?

**Comment by agronholm** [comment]
One thought occurred to me: have you tried creating a fresh virtualenv and installing cbor2 there? Setuptools_scm should be able to pick up the version from the `PKG_INFO` file in the source tarball, but I'm not sure if that has always been the case.

**Comment by SmithSamuelM** [comment]
When I get a minute Iwill try. I spent a lot of time finding the problem and a fix and now have to get caught up on work

**Comment by SmithSamuelM** [comment]
I thin the problem is this is broken using a post release version specifier

% pip3 install -U cbor2

The -U is trying to install a later version,  but. https://peps.python.org/pep-0440/. indicates that any post “.post” release indicators in a version are ignored. So it can’t find it.  In general this breaks anyones build that lists cbor2 as a dependency.  Being able tomanually install cbor2 from the command line is not a solution. I want it to get updated automatically as a dependency using a requirements specification and when you use post release versioning you break that. So scm should not be used with post release. Its just a bad idea.  Don’tj do it.

**Comment by agronholm** [comment]
It seems that you misunderstanding something. The 5.4.2.post1 release was made only to release binary wheels that the original 5.4.2 release did not have. There were no actual code changes between the two releases. If 5.4.2 is already installed, `pip install -U` won't replace 5.4.2 with 5.4.2.post1, and that's totally fine.

From PEP 440:

> Some projects use post-releases to address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes).

**Comment by agronholm** [comment]
Did you try installing in a fresh virtualenv yet?

**Comment by SmithSamuelM** [comment]
In my case 5.4.2 was not installed. It was upgrading from 5.4.1 and couldn’t. Binary wheels ARE affecting the distributed software so shouldn’t be a .post release.

**Comment by agronholm** [comment]
Before I engage in this discussion any further, I insist that you try with a fresh virtualenv (without `--system-site-packages``). I have a lingering suspicion that your problem is caused by an old version of `setuptools_scm` which cannot read the PKG-INFO of the source tarball.

**Comment by agronholm** [comment]
And installing from the PyPI source tarball worked fine for me, as I demonstrated earlier. The binary wheels would be a non-factor in such case.

**Comment by Sekenre** [comment]
> Before I engage in this discussion any further, I insist that you try with a fresh virtualenv (without `--system-site-packages`). I have a lingering suspicion that your problem is caused by an old version of `setuptools_scm` which cannot read the PKG-INFO of the source tarball.

I can confirm this, I had the same problem and it was fixed by installing a fresh env with the latest setuptools and setuptools_scm.

**Comment by agronholm** [comment]
> > Before I engage in this discussion any further, I insist that you try with a fresh virtualenv (without `--system-site-packages`). I have a lingering suspicion that your problem is caused by an old version of `setuptools_scm` which cannot read the PKG-INFO of the source tarball.
> 
> I can confirm this, I had the same problem and it was fixed by installing a fresh env with the latest setuptools and setuptools_scm.

It should not be necessary to explicitly install either in a fresh virtualenv. Can you confirm?

**Comment by Sekenre** [comment]
Here's my environment that re-creates this problem:
```
(cbor) me@redacted ~/Projects/cbor2 $ python setup.py --version
~/miniconda3/envs/cbor/lib/python3.7/site-packages/setuptools_scm/integration.py:39: RuntimeWarning:
ERROR: setuptools==41.0.1 is used in combination with setuptools_scm>=6.x

Your build configuration is incomplete and previously worked by accident!


This happens as setuptools is unable to replace itself when a activated build dependency
requires a more recent setuptools version
(it does not respect "setuptools>X" in setup_requires).


setuptools>=31 is required for setup.cfg metadata support
setuptools>=42 is required for pyproject.toml configuration support

Suggested workarounds if applicable:
 - preinstalling build dependencies like setuptools_scm before running setup.py
 - installing setuptools_scm using the system package manager to ensure consistency
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  """
~/miniconda3/envs/cbor/lib/python3.7/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('5.4.2.post1.post10+dirty') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
5.4.2.post1.post10+dirty

```

**Comment by Sekenre** [comment]
Updating setuptools did not fix the issue.

**Comment by agronholm** [comment]
PRs #133 and #132 should hopefully fix this.

**Comment by Sekenre** [comment]
I think setuptools_scm can't handle it when the last version tag has ".post1" at the end. This breaks building from the main branch. I have made it work in some circumstances but I can't figure out __why__ it works.

**Comment by agronholm** [comment]
Does it work with plain `5.4.2` then?

**Comment by agronholm** [comment]
BTW, setuptools_scm should not be adding anything to the version when it's running directly against a git tag. Are you saying you're seeing this happening?

**Comment by Sekenre** [comment]
> BTW, setuptools_scm should not be adding anything to the version when it's running directly against a git tag. Are you saying you're seeing this happening?

No, if I checkout tag 5.4.2.post1 and then run `python setup.py --version` it works fine. The only issue appears if you're building from master or you have local changes. That's why I opened pypa/setuptools_scm#709

**Comment by agronholm** [comment]
Yeah, that I am seeing too. Does it help if you nix our setuptools_scm configuration?

**Comment by Sekenre** [comment]
I have tried multiple combinations of setuptools_scm they all seem to do the same thing. I can't re-create the situation I saw where it worked from tox.

It might be easier to just create a new tag major.minor.rel once we finish removing python 3.6 support

**Comment by agronholm** [comment]
> It might be easier to just create a new tag major.minor.rel once we finish removing python 3.6 support

That definitely requires a new version anyway. The post releases are only for cases where nothing but the packaging has changed, like when we just added more binary wheels.

**Comment by agronholm** [comment]
To put it differently, post-releases should offer nothing to anybody who has already successfully installed the base release.

**Comment by Sekenre** [comment]
Ok, we worked it out.

If you change the "version_scheme" setting for setuptools_scm to `"guess-next-dev"` it behaves like I expected it to, incrementing `.postN` and adding `.dev{distance}`

**Comment by agronholm** [comment]
IIRC that is the default setting. This is why I asked before if nixing the setuptools_scm configuration solved the issue :)
Feel free to change it however you like – I'm not particularly attached to any specific settings there.

**Comment by SmithSamuelM** [comment]
5.4.3 release installed just fine.
BTW you might find this blog post interestingly relevant. It details a parsing vexation in PIP packaging that I believe this issue ran afoul off.   https://blog.yossarian.net/2022/05/09/A-most-vexing-parse-but-for-Python-packaging

Note the example near the end of the   document where

```python
>>> from packaging.version import parse
>>> parse("1.0.2-2")
<Version('1.0.2.post2')>
```

**Comment by agronholm** [comment]
This project only ever used PEP 440 compliant versioning numbers so the post you linked to doesn't apply.

**Comment by SmithSamuelM** [comment]
Done removed fork. Frankly @agronholm you should read the whole article. The parsing problem is not as simple as using PEP 440 versioning but involves how source and wheel distributions are matched to versions which is directly relevant to the problem encountered here. I think you are too quick to dismiss relevant information. =)

**Comment by agronholm** [comment]
I did read it, but it deals with old distributions. Quote from the beginning:
> A great deal of emphasis is on minor: this ambiguity appears in relatively old package distributions, and is addressed by both package name normalization ([PEP 426](https://peps.python.org/pep-0426/#name)) and version normalization ([PEP 440](https://peps.python.org/pep-0440/#normalization)), each of which builds off of earlier “canonical” specifications of distribution names and versions.

What, in your opinion, did I miss?

**Pull request closed without merging**
