### PR TITLE
Fixed infinite recursion on recursive hash() on CBORTag

### PR DESCRIPTION
**Pull request by agronholm**
Relates to #198.

### CODE REVIEW

**Comment by agronholm** [comment]
This was no low hanging fruit, I tell you :) It was the hardest fix to date, for me at least.

**Comment by agronholm** [comment]
What input is producing segfaults now? I only remember one being mentioned, but I fixed that one already.

**Comment by mschwager** [comment]
> This was no low hanging fruit, I tell you :) It was the hardest fix to date, for me at least.

Sorry, I meant low hanging fruit for the fuzzer to find crashes, not for the fix. By low hanging fruit I just meant the fuzzer was able to find the crashes in minutes or hours rather than days or weeks of runtime :+1: 

> What input is producing segfaults now? I only remember one being mentioned, but I fixed that one already.

As far as segfault crashes, there were two:

- https://github.com/agronholm/cbor2/issues/198#issuecomment-1869630196
- https://github.com/agronholm/cbor2/issues/198#issuecomment-1869730701

I re-ran the fuzzer against this branch and neither of those crashes, or any others, appeared after a few hours of runtime.

**Comment by agronholm** [comment]
Ok, we're on the same page then. Perhaps the `MemoryError` still needs to be investigated, but the rest of the errors just need to be wrapped in `CBORDecodeError`.

**Pull request merged**
